export const STATUS_PENDING = "PENDING";
export const STATUS_APPROVED = "APPROVED";
export const STATUS_REJECTED = "REJECTED";
export const VALID_STATUSES = [
  STATUS_PENDING,
  STATUS_APPROVED,
  STATUS_REJECTED,
];
